### ISSUE TITLE
Puzzle Toolbars is completely broken on current Nightly

### ISSUE THREAD

**Issue by the-nothingman** [Quicksaver/Puzzle-Toolbars#83]
just as the title says, I have no clue what the issue is but with the addon enable the result is the same. Non of the toolbar created by the addon are visible or selectable in any fashion 
Nightly 44.0a1 (2015-10-08)

**Comment by Quicksaver** [comment]
I'm sure this is related to [bug 1212293](https://bugzilla.mozilla.org/show_bug.cgi?id=1212293). In short, tomorrow's nightly should be fine. Even if it isn't, I've already fixed it locally for when the culprit patch lands for good, I just need to upload it.

**Comment by the-nothingman** [comment]
whatever was suppose to land in today's Nightly to fix the issue did not, its still broken

**Comment by Quicksaver** [comment]
Indeed I've heard. :( Good news is everything is still fine for me, so my fix does seem to work. Care to try beta version 2.1.5b3 which I just uploaded to https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.5b3?
