### ISSUE TITLE
Tab Groups 'title icon' Incompatible with Puzzle Bars [location bar]

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Puzzle-Toolbars#98]
#### Transfered over from > :link:[Issue #438: Tab Groups 'title icon' Incompatible with Puzzle Bars](https://github.com/Quicksaver/Tab-Groups/issues/438)
***
Thanks for the improvements in this beta, as you can see the TG title button does now display on PB…
…now here's the newly emerging issue when I enable Tab Groups' '**<ins>show current group's title</ins>**' setting on the button in Puzzle Bars' **<ins>location bar</ins>**:  
*<samp>Hover your cursor over each image below for a description.</samp>*
:one: Before any changes >>> ![2016-10-21_190600](https://cloud.githubusercontent.com/assets/364460/19614297/b0396b32-97c1-11e6-965d-66ca566092a2.png "location bar with the tab groups icon on it")
:two: After switching from Icon to Title >>> ![2016-10-21_183953](https://cloud.githubusercontent.com/assets/364460/19614070/4655f73c-97bf-11e6-92fc-3a88756896a9.png "several buttons' icons are pushed out of view")
:three: What should be on the bar >>> ![2016-10-21_181658](https://cloud.githubusercontent.com/assets/364460/19614053/17a89714-97bf-11e6-81f8-1201fad918f7.png "location bar as it should look")
:four: After changing it back to an icon >>> ![2016-10-21_182919](https://cloud.githubusercontent.com/assets/364460/19614099/836b8d30-97bf-11e6-8abf-5920d4569aa1.png "notice the large gap highlighted in yellow")  
The issues are on items :two: & :four:; they are fixed by entering then exiting the customization interface.

:small_orange_diamond: <samp>I tried it on the **<ins>corner bar</ins>** and didn't encounter any of the issues above, this only seems to involve the **<ins>location bar</ins>**.</samp>

**Comment by Quicksaver** [comment]
Good catch. Should be fixed in [beta version 2.1.15b2](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b2), note that you also need the lastest [Tab Groups beta 2.1b7](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b7) for the fix to work properly.

**Comment by jmain33** [comment]
:pensive: Still happens when running both of the latest betas.

I still need to enter the customization interface in order for the 'location puzzle bar' to be properly refreshed. No change in any of the behavior.

<ins>Alternatively</ins>: I've found that clicking another button on the puzzle bar will also invoke an update of its button placement. Unfortunately no buttons, _besides the Tab Groups button_, are visible when I switch from <kbd>icon button</kbd> :arrow_right: <kbd>title button</kbd>.

**Comment by Quicksaver** [comment]
Yep, you're right, [Tab Groups 2.1b8](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b8) and [Puzzle Bars 2.1.15b3](https://github.com/Quicksaver/Puzzle-Toolbars/releases/tag/v2.1.15b3) should work well now.

**Comment by jmain33** [comment]
:tada: Excellent the transition is flawless now!
Have a good weekend.
